dist: xenial
language: python
python:
- 3.8
- 3.9
install:
- pip install -e .[tests]
script:
- pytest -v tests
deploy:
  provider: pypi
  username: __token__
  password:
    secure: crSt6h+MaJbZB8V9kerTx8hJxv7jXFjNH3SB2XWc70aOypnXMa02+NrjPwwXqb29zupH5TzshjW3g0yBPq0eIQgsrnTbhDJdbuUk8gAM0J6MvUzXfVDObvuVatAJdv+OfjgWqituqDg3yInfrKBjkDBX/gIPfMcCs+vSz5JYc0R7D9brWiPT/ipdJOYK0eoFdmKnslACAIfnku6/a0nDCvtPR/5xhqRIX+IJKlIEhrwRgsmKoF7eeeYYMiwS+Ja74cfS9aSRTMmcey/GvYftx3+uHD8v2giHM8GBd32rj5RhsqdLL8HKEj2hWRoI1JonAHsBiEDHKQKN3wK/JwWRj02CmADybQtHZJHF6EKLupk55O2z14+WASkr9UAwap+OdoU07FOOzEMcDi0kl8oAJkMBaAASm6fqjlwyHz5bBF9TdzZ5x/Vgog9Ipu8kDgIVTvHzBfV0oRZEWYOegNVgBfLtPv0Q1uINVV320UQ/Oc6N/L3oOk0vz0wVees0HmxMWnWE93FD2DCGOp5QWzq9AvgiKOhyBtRpQ9oD2QJDfh7Xb97vws56WwGwkFcn7a5Py6aWuP2Zrlkc+SJ74CL9FS9y6wwYYNK04Cza8fj/Fcmcw4KMs9j47ls4+RDY9yz/1JPz/6LkuEmNLXq5iZFFdqTL9rdJpZ7LKky3fccQqB4=
  on:
    tags: true
    python: 3.9
